spring:
  application:
    name: logcollect-sample-boot34-log4j2
  config:
    import: "classpath:application-common.yml"

sample:
  module-id: logcollect-sample-boot34-log4j2
  boot-version: 3.4.1
  logging-framework: log4j2

logcollect:
  global:
    log-framework: LOG4J2
